const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "255752264609";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,255752264609";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,255752264609";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,255752264609"; by

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_16_14_10_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgMjM2LFxuICAgICAgICAxMzQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMzEsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMjgsXG4gICAgICAgIDIwLFxuICAgICAgICAxMDksXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjMsXG4gICAgICAgIDE1LFxuICAgICAgICAyNSxcbiAgICAgICAgMTM4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMyxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjM3LFxuICAgICAgICAyNTMsXG4gICAgICAgIDM3LFxuICAgICAgICA2NixcbiAgICAgICAgMjQ3LFxuICAgICAgICA1NyxcbiAgICAgICAgMzQsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNzUsXG4gICAgICAgIDEyNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTEsXG4gICAgICAgIDc2LFxuICAgICAgICAxNixcbiAgICAgICAgMTM3LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE5LFxuICAgICAgICA4MixcbiAgICAgICAgMTYyLFxuICAgICAgICA2OSxcbiAgICAgICAgOTksXG4gICAgICAgIDg4LFxuICAgICAgICA4NyxcbiAgICAgICAgMzksXG4gICAgICAgIDU0LFxuICAgICAgICA1MCxcbiAgICAgICAgMjA5LFxuICAgICAgICAyMjgsXG4gICAgICAgIDk2LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE3LFxuICAgICAgICAxMSxcbiAgICAgICAgNzQsXG4gICAgICAgIDMyLFxuICAgICAgICAyNDQsXG4gICAgICAgIDQ1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMzEsXG4gICAgICAgIDI0NixcbiAgICAgICAgODEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICA5NixcbiAgICAgICAgMTk2LFxuICAgICAgICAxODcsXG4gICAgICAgIDY0LFxuICAgICAgICAyMjksXG4gICAgICAgIDEwMixcbiAgICAgICAgOTAsXG4gICAgICAgIDE1OSxcbiAgICAgICAgODYsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTY1LFxuICAgICAgICAyMDYsXG4gICAgICAgIDU1LFxuICAgICAgICAxMjAsXG4gICAgICAgIDY1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDcyLFxuICAgICAgICA1NixcbiAgICAgICAgOTYsXG4gICAgICAgIDE5LFxuICAgICAgICAxNyxcbiAgICAgICAgMTY0LFxuICAgICAgICA4MyxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMDQsXG4gICAgICAgIDcyLFxuICAgICAgICAxODksXG4gICAgICAgIDcyLFxuICAgICAgICAxNjgsXG4gICAgICAgIDI1LFxuICAgICAgICAxMDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDE4NCxcbiAgICAgICAgNTcsXG4gICAgICAgIDg0LFxuICAgICAgICAxOCxcbiAgICAgICAgMSxcbiAgICAgICAgMjIyLFxuICAgICAgICAzNCxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMTEsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTQzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTQxLFxuICAgICAgICAxODUsXG4gICAgICAgIDcxLFxuICAgICAgICA5MSxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNTksXG4gICAgICAgIDU1LFxuICAgICAgICA1LFxuICAgICAgICA3MixcbiAgICAgICAgMTQ5LFxuICAgICAgICA3LFxuICAgICAgICA5NixcbiAgICAgICAgMTU3LFxuICAgICAgICAzOSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMjgsXG4gICAgICAgIDU1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3MixcbiAgICAgICAgMjQsXG4gICAgICAgIDcsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNzQsXG4gICAgICAgIDM2LFxuICAgICAgICAxOCxcbiAgICAgICAgMTczLFxuICAgICAgICA0NCxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNzIsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjE5LFxuICAgICAgICAxNjcsXG4gICAgICAgIDIyMyxcbiAgICAgICAgOTIsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTAwLFxuICAgICAgICAxODQsXG4gICAgICAgIDI2LFxuICAgICAgICAyNDgsXG4gICAgICAgIDk5LFxuICAgICAgICA5NSxcbiAgICAgICAgMTI4LFxuICAgICAgICAyNDYsXG4gICAgICAgIDkxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTgxLFxuICAgICAgICAyMDAsXG4gICAgICAgIDIzOSxcbiAgICAgICAgODdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzksXG4gICAgICAgIDE5NyxcbiAgICAgICAgNDIsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMjYsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNzcsXG4gICAgICAgIDIxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDIzNyxcbiAgICAgICAgODcsXG4gICAgICAgIDIyLFxuICAgICAgICAyMTMsXG4gICAgICAgIDQ1LFxuICAgICAgICA3NSxcbiAgICAgICAgMjUzLFxuICAgICAgICAxMTIsXG4gICAgICAgIDYwLFxuICAgICAgICA0OSxcbiAgICAgICAgMjQwLFxuICAgICAgICAzNCxcbiAgICAgICAgNixcbiAgICAgICAgMTY4LFxuICAgICAgICAxMCxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTksXG4gICAgICAgIDIzOSxcbiAgICAgICAgNjQsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTIxLFxuICAgICAgICAyNTUsXG4gICAgICAgIDMyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDEyN1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxMTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjEsXG4gICAgICAgIDUyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDM2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDUsXG4gICAgICAgIDI4LFxuICAgICAgICAzMyxcbiAgICAgICAgMzEsXG4gICAgICAgIDYsXG4gICAgICAgIDc1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDg2LFxuICAgICAgICAxNTIsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjQzLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTk1LFxuICAgICAgICA4NyxcbiAgICAgICAgMTM2LFxuICAgICAgICAxNzUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMzUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgODQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTIyLFxuICAgICAgICA5NyxcbiAgICAgICAgMTU5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTQ0LFxuICAgICAgICA5NSxcbiAgICAgICAgODYsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTc5LFxuICAgICAgICA4MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDAsXG4gICAgICAgIDEzLFxuICAgICAgICA3NCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTgwLFxuICAgICAgICAxODUsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjI2LFxuICAgICAgICA5MyxcbiAgICAgICAgODQsXG4gICAgICAgIDExNixcbiAgICAgICAgMTcxLFxuICAgICAgICAyOCxcbiAgICAgICAgMTksXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDM5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDMxLFxuICAgICAgICAxMDAsXG4gICAgICAgIDU5LFxuICAgICAgICAxNDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE4NCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJ1MjAvQmNUQk0wZkxSN0Z2YkN2WlUvWU1rZ0IxWERBYWpLbUN3dnFEWXlnPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJHTnJYUU5KOVJ0aWdlOHd6amJ0c25nXCIsXG4gIFwicGhvbmVJZFwiOiBcIjEyNGQ2ODA4LTMwYjItNDc0OS1hNjQ3LTZkMjZhNTFmMTRhMFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA2NyxcbiAgICAgIDE1MixcbiAgICAgIDI0LFxuICAgICAgMTgyLFxuICAgICAgMTg2LFxuICAgICAgODYsXG4gICAgICAxNTIsXG4gICAgICAxNDQsXG4gICAgICAxODQsXG4gICAgICAxNTYsXG4gICAgICA0OCxcbiAgICAgIDIyOSxcbiAgICAgIDE4MSxcbiAgICAgIDYyLFxuICAgICAgMTIwLFxuICAgICAgMTIwLFxuICAgICAgMTcxLFxuICAgICAgMTQzLFxuICAgICAgNzMsXG4gICAgICAyMTVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTEyLFxuICAgICAgMTAxLFxuICAgICAgOTUsXG4gICAgICAyMzYsXG4gICAgICAyNDEsXG4gICAgICAxNDgsXG4gICAgICAxNTAsXG4gICAgICA0MSxcbiAgICAgIDYzLFxuICAgICAgMTA0LFxuICAgICAgOTQsXG4gICAgICAyMDYsXG4gICAgICAxMTgsXG4gICAgICAyMTMsXG4gICAgICA0NSxcbiAgICAgIDQ3LFxuICAgICAgNDEsXG4gICAgICA4MSxcbiAgICAgIDQ0LFxuICAgICAgMTc0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjVRQjlaUTVTXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTU3NTIyNjQ2MDk6MzJAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJPbWFyeSDvo79cIixcbiAgICBcImxpZFwiOiBcIjI3MTM2MDc2NDk5NzcyNDozMkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQL3lyNkVMRU4vQjVMZ0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIm1KVm1meVNjL1E0TnlneW1MbjJ2ajh6UWdzVklwdXlyREJueWJGWkVDMlE9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiR0VuaiswNElqVEpVcEprSUxBUnNGZW9TS0VoZ245SDJSZVJQeUFhbmRSUWNzeW1uZXhuUE1BdmxpRlRFRnd4ajEvcVZ3bTZmb04rdWR3aHpsZ1V2RHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiaXdzcFpiRFcwY2xMNTF1d1A2b3VSdCtScVFIRmFxZmZZeWU2d2FhY2tvZFFOcGVTQTVIeG1tdVZscUR5RTNQSWdoa3d2WGQyNnlROUFnaDlOc2ZHakE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU1NzUyMjY0NjA5OjMyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA4NixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAxMDBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmlcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyOTcwMDA4OSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUJNUFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQk1QLmpzb24iOiAie1wia2V5RGF0YVwiOlwidlkrSmZRWEdsbWRrMmtPdk9uRkkydTVsSXNELzJUVGMxYVRTTGhwL1Jvdz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMDIyNzgwNzk5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3Mjk3MDAwOTUyOTZcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
